//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreGameEngine.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoreGameEngine.Resources.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given argument is null.
        /// </summary>
        internal static string Argument_IsNull {
            get {
                return ResourceManager.GetString("Argument_IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {0} cannot be empty.
        /// </summary>
        internal static string Argument_StringEmpty_ExceptionTakesParam {
            get {
                return ResourceManager.GetString("Argument_StringEmpty_ExceptionTakesParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given jagged array is not rectangular.
        /// </summary>
        internal static string Array_JaggadNotRectangular {
            get {
                return ResourceManager.GetString("Array_JaggadNotRectangular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix must be square.
        /// </summary>
        internal static string Array_MatrixNotSquare {
            get {
                return ResourceManager.GetString("Array_MatrixNotSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The background task is already running.
        /// </summary>
        internal static string BackgroundAction_AlreadyRunning {
            get {
                return ResourceManager.GetString("BackgroundAction_AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval cannot be less than one.
        /// </summary>
        internal static string BackgroundAction_IntervalLessThanOne {
            get {
                return ResourceManager.GetString("BackgroundAction_IntervalLessThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The background task is not currently running.
        /// </summary>
        internal static string BackgroundAction_NotRunning {
            get {
                return ResourceManager.GetString("BackgroundAction_NotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection cannot be empty.
        /// </summary>
        internal static string Collection_CannotBeEmpty {
            get {
                return ResourceManager.GetString("Collection_CannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary cannot contain null values.
        /// </summary>
        internal static string Dictionary_CannotContainNullValues {
            get {
                return ResourceManager.GetString("Dictionary_CannotContainNullValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dictionary does not contain the given key.
        /// </summary>
        internal static string Dictionary_InvalidKey {
            get {
                return ResourceManager.GetString("Dictionary_InvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dictionary already contains the given key.
        /// </summary>
        internal static string Dictionary_KeyAlreadyExists {
            get {
                return ResourceManager.GetString("Dictionary_KeyAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registry does not contain the given key.
        /// </summary>
        internal static string Factory_InvalidKey {
            get {
                return ResourceManager.GetString("Factory_InvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registry already contains the given key.
        /// </summary>
        internal static string Factory_KeyAlreadyExists {
            get {
                return ResourceManager.GetString("Factory_KeyAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given parameter is of the incorrect type.
        /// </summary>
        internal static string Parameter_IncorrectType {
            get {
                return ResourceManager.GetString("Parameter_IncorrectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided shape expression is not a valid pattern.
        /// </summary>
        internal static string Shape_InvalidShapeRegex {
            get {
                return ResourceManager.GetString("Shape_InvalidShapeRegex", resourceCulture);
            }
        }
    }
}
